application: invoicecloud-1143
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: InvoiceCloud.wsgi.application

libraries:
- name: django
  version: "latest"
- name: MySQLdb
  version: "latest"
